CONVERT_TO = rp2040_ce

USER_NAME := r58iiz

RGB_MATRIX_CUSTOM_USER = yes

VIA_ENABLE = yes
VIAL_ENABLE = yes
VIALRGB_ENABLE = yes

COMBO_ENABLE = yes
ENCODER_MAP_ENABLE = yes
EXTRAKEY_ENABLE = yes
MOUSEKEY_ENABLE = yes